version: '3'
services:
  db:
    image: postgres:13
    container_name: pg
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
volumes:
  data: